apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ziyad-tarek1/DevOps-EKS-GitOps-ActionFlow.git
    targetRevision: HEAD
    path: kubernetes/service
  destination:
    server: https://kubernetes.default.svc
    namespace: skyebank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
