---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyebank-app
  namespace: skyebank
  labels:
    app: skyebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skyebank
  template:
    metadata:
      labels:
        app: skyebank
    spec:
      containers:
      - name: skyebank
        image: 135808945423.dkr.ecr.us-east-1.amazonaws.com/skyebank:v2.4 
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080 
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080  
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          runAsUser: 1001
          runAsGroup: 3001
          allowPrivilegeEscalation: false
