---
apiVersion: v1
kind: Service
metadata:
  name: skyebank-service
  namespace: skyebank
  labels:
    app: skyebank
spec:
  selector:
    app: skyebank
  ports:
  - protocol: TCP
    port: 8080  
    targetPort: 8080
  type: ClusterIP
