name: Terraform Apply

# Note: Uncomment The Below if You Want Auto Apply 
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "infrastructure/**"

on:
  workflow_dispatch:

permissions:
  id-token: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: |
        cd infrastructure/production
        terraform init -backend=true -input=false

    - name: Terraform Apply
      id: apply
      run: |
        cd infrastructure/production
        terraform apply -auto-approve -input=false
